### ISSUE TITLE
CFR Master Maps: List of additional features required for the interactive map of each CFR Master Map record (Map features)

### ISSUE THREAD

**Issue by ygoex** [National-Forestry-Authority/brms#22]
**This is for the map on the dashboard that shows all the CFRs on one single map.**

There should be an interactive map on the main CFR Master Map list view (page) (https://brms.cambrico.net/cfr) above the filter(s). We should take as reference this: https://forests.nfa.go.ug/ 

For each CFR record, the interactive map needs:
  -  A layer control widget to control the visibility of the following layers (the list may grow):
  - Old polygon (the one we have now, very inaccurate) - in grey (coordinates)
  - Newly digitized polygon - **Cutline** - solid line
                                              - **Inter-protected area cutline** -
                                              - **Natural boundary - water** - dashed line
                                              - **Natural boundary - ridge** - dashed line
  - Location of pillars / way points - **Cardinal / corner pillars** - red circle with an annotation of pillar and coordinates
                                                        - **Intermediate pillars** - red dot with an annotation of pillar and coordinate
 - Range boundaries - in purple
 - Sector boundaries - in orange

There should be form fields for each of these additional attributes.  
   - All layers can be turned on and off at the layer control widget.

A key security feature is that once uploaded, geospatial data cannot be removed from the system (without admin intervention). This ensures that data-tampering is more difficult to effect.

Provide a way to upload the kml and provide a polygon textarea.

**Comment by ygoex** [comment]
We need to put constraints on the colours used by the editors.

We would need around 20 colours with a standard line with a single width, and dash, dotted and solid styles for the time being.

**Comment by peacog** [comment]
Closing in favor of [Forest Reserves overview: Overview map on main dataset listing view#7](https://github.com/National-Forestry-Authority/brms/issues/7)
