### ISSUE TITLE
User activity tracker

### ISSUE THREAD

**Issue by ygoex** [National-Forestry-Authority/brms#44]
Track the activity of users through the system.

**Comment by ygoex** [comment]
This module might help with this issue: https://www.drupal.org/docs/8/core/modules/tracker-module/overview

**Comment by ygoex** [comment]
We'll apply here the same approach described here: https://github.com/National-Forestry-Authority/farmers/issues/133#issuecomment-1519801419

**Comment by peacog** [comment]
NFA tracker module has been installed. The user reports are in the Administration > Reports section of the site https://brms.stg.envs.utils.nfa.go.ug/admin/reports/nfa/tracker

**Comment by LeScruf** [comment]
@peacog This is looking promising - I am wondering currently it just tells you who accessed what, but the log doesn't provide any more information about what happened when the user accessed a particular node? Is there any built-in functionality within Drupal Core or an existing module that provides further functionality in this regard?

**Comment by peacog** [comment]
Hi @LeScruf . The report tells you when node was saved and by whom. It doesn't tell you about when nodes are views/accessed. If more information is needed we would have to build a custom solution. @pcambra suggested using the Log module in this related ticket for farmers: https://github.com/National-Forestry-Authority/farmers/issues/133#issuecomment-1439961434.

The first step would be to describe what kinds of activity you want to report on. Could you make a list of what events you would like to track?

**Comment by peacog** [comment]
@LeScruf 
I think you have already tested this. Do you want to add more requirements and move to **Functional WIP**? Or will we mark it **_Done_**?

**How to test**
Review the User content activity tracker: https://brms.stg.envs.utils.nfa.go.ug/admin/reports/nfa/tracker/content


![Image](https://github.com/National-Forestry-Authority/brms/assets/1312689/e7ba6b8d-bd7b-4cd3-8f4c-03b0d2425f60)

**Comment by ygoex** [comment]
Closing it as it is completed.
