### ISSUE TITLE
Hide District 2 tab on Forest Reserve form

### ISSUE THREAD

**Issue by peacog** [National-Forestry-Authority/brms#94]
Some Forest Reserves have two reserve serial numbers and associated district/county records. This data is in the District 2 tab on the forest reserve edit form. The District 2 tab should not be visible if it has no data, but we need an option to make it visible so that district 2 data can be added.

- [ ] Hide the District 2 tab if the forest reserve serial number 2 and District 2 fields are empty
- [ ] Add a toggle option to show/hide the tab

![Image](https://user-images.githubusercontent.com/1312689/254499766-5efb7c5e-22cf-43ca-b97d-81d5e7ea7da6.png)

**Comment by peacog** [comment]
The tabs are provided by the Field Group module. Field Group has its own form hooks that run after core form hooks, which means we can't use states in the normal way in hook_form_alter. I tried some suggestions in this issue https://www.drupal.org/project/field_group/issues/1053174#comment-12234371 but I could not make it work.

If we can't get states to work we could do it with custom javascript attached to the forest reserve form. 

The toggle could be implemented like the Show row weights link that is show on draggle lists, such as a content type form display page, for example https://brms.stg.envs.utils.nfa.go.ug/admin/structure/types/manage/forest_reserve/form-display


![Image](https://github.com/National-Forestry-Authority/brms/assets/1312689/071ebc29-640c-41ab-8ed4-193dd8351f1a)

**Comment by ygoex** [comment]
Since we are not going to have two tabs anymore and we are going to have only one Districts tab, this ticket is obsolete.
